# Generated by Django 3.0.3 on 2020-10-02 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-id', '-timestamp'),
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('abbr', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('abbr',),
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.TextField(blank=True, null=True)),
                ('middle', models.TextField(blank=True, null=True)),
                ('last', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_name', to='contact.Contact')),
            ],
            options={
                'ordering': ('-last', '-first', '-timestamp'),
                'get_latest_by': 'timestamp',
            },
        ),
    ]
