# Generated by Django 3.0.3 on 2020-10-02 11:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField()),
                ('factor', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-group', 'factor'),
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_factor', to='element.Factor')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_child', to='element.Element')),
            ],
            options={
                'ordering': ('-id', '-factor'),
            },
        ),
    ]
